# Generated by Django 5.2.8 on 2025-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(verbose_name=255)),
                ('P_number', models.IntegerField(verbose_name=10)),
                ('P_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
