# Generated by Django 5.2.8 on 2026-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_course_course'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stud',
            field=models.CharField(default='n', max_length=200),
            preserve_default=False,
        ),
    ]
