# Generated by Django 5.2.8 on 2026-02-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_student_managers_student_stud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud',
        ),
    ]
